# Generated by Django 4.0.5 on 2022-12-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.TextField(blank=True, max_length=10, verbose_name='цена'),
        ),
    ]
