# Generated by Django 4.0.5 on 2023-01-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.TextField(max_length=150)),
                ('product', models.ForeignKey(blank=True, default='', null=True, on_delete=models.Model, to='myshop.product')),
            ],
        ),
    ]
