# Generated by Django 4.1.5 on 2023-01-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0009_basket_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='product',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product/%Y/%m/%d')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.TextField(max_length=150)),
                ('order', models.ForeignKey(blank=True, default='', null=True, on_delete=models.Model, to='myshop.product')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='order',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=models.Model, to='myshop.order'),
        ),
    ]
