# Generated by Django 4.1.5 on 2023-01-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0010_remove_basket_product_orders_basket_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basket',
            new_name='Baskets',
        ),
    ]
